# 2.1 Data Manipulation

## Table of Contents
[2.1.1 Getting Started](#start)

[2.1.2 Operations](#operation)

[2.1.3 Broadcasting Mechanism](#broad)

[2.1.4 Indexing and Slicing](#index)

[2.1.5 Saving Memory](#mem)

[2.1.6 Conversion to Other Python Objects](#conv)

[2.1.7 Summary](#sum)

[2.1.8 Exercises](#ex)


## 2.1.1 Getting Started <a name="start"></a>

In [1]:
# Import Pytorch
import torch

A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor corresponds (in math) to a *vector*. With two axes, a tensor corresponds to a *matrix*.

Each of the values in a tensor is called an **element of the tensor**. Unless otherwise specified, a new tensor will be stored in main memory and designated for **CPU-based computation**.

In [2]:
# Construct synthetic tensor
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# Access the tensor shape
x.shape

torch.Size([12])

In [5]:
# Retrieve the total number of elements in a tensor
x.numel() # num of elements

12

In [11]:
# Reshape the tensor without altering the value and number of the elements
X = x.reshape(3,4)
print(X)
print('\n')

# Manually specifying multiple dimensions are not necessary. We can specify -1 and pytorch will invoke the corresponding value
X_ = x.reshape(3, -1)
print(X_)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [12]:
# Create a tensor with all elements set to 0
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# Create a tensor with all elemnets set to 1
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
# Create a tensor with reandomly sampled values
torch.randn(3, 4)

tensor([[-2.4676, -1.2175, -0.3053, -0.1694],
        [-0.7237,  0.0891,  0.4163,  0.9658],
        [-1.1075,  0.2956, -0.0222,  0.5034]])

In [16]:
# Specify the values of each element by providing python list
torch.tensor([[2,1,4,3],
            [1,2,3,4],
            [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 Operations <a name="operation"></a>

In [17]:
# Arithmetic operations have all been lifted to elementwise operations
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [18]:
# Exponentiation is also applied elementwise
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
# Tensor concatenation
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))
print('\n')
print(torch.cat((X, Y), dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [21]:
# Logical Operatior also apply elementwise
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
# Summing up all the elements
X.sum()

tensor(66.)

## 2.1.3 Broadcasting Mechanism <a name="broad"></a>

Under certain conditions, even when shapes differ, we can still perform elementwise operations by invoking the broadcasting mechanism. 

1. Expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape.

2. Carry out the elementwise operations on the resulting arrays.

In [23]:
# Set up example
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Although a and b are of different shape, We broadcast the entries of both matrices into a larger  $3×2$  matrix as follows: for matrix $a$ it **replicates the columns and for matrix $b$ it replicates the rows before adding up both elementwise**.



In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 Indexing and Slicing <a name="index"></a>

Similar to Python array, elements in a tensor can be accessed by index.

In [25]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [29]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Beyond reading, we can also write elements of a matrix by specifying indices.

In [30]:
# Write single value
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
# Write multiple values at the same time
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 Saving Memory  <a name="mem"></a>

In [32]:
before = id(Y)
Y = Y + X
id(Y) == before

False

After running $Y = Y + X$, we will find that **id(Y)** points to a different location. That is because Python **first evaluates $Y + X$**, allocating new memory for the result, and then **makes Y point to this new location in memory**.

This might be undesirable for two reasons.
1. We do not want to allocate unnecessary memory usage. Typically, we want to perform these updates **in place**.
2. If we do not update in place, some references might point to the old reference, making part of the code to break. 

In [34]:
Z = torch.zeros_like(Y) ## Returns a tensor filled with `0`, with the same size as the input
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140296723607296
id(Z): 140296723607296


## 2.1.6 Conversion to Other Python Objects  <a name="conv"></a>

In [38]:
# Converting numpy to tensor and vice versa
A = X.numpy() ## convert to numpy
B = torch.tensor(A) ## convert back to tensor

type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [39]:
# Convert size-1 tensor to a python scalar
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7 Summary <a name="sum"></a>

* The main interface to store and manipulate data for deep learning is the tensor ( 𝑛 -dimensional array). It provides a variety of functionalities including basic mathematics operations, broadcasting, indexing, slicing, memory saving, and conversion to other Python objects.

## 2.1.8 Exercises <a name="ex"></a>

1. Run the code in this section. Change the conditional statement X == Y in this section to X < Y or X > Y, and then see what kind of tensor you can get.

In [45]:
# Tensor concatenation
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

## X > Y and X < Y are still elementwise
X > Y, X < Y

(tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?



In [48]:
a = torch.arange(6).reshape((3,2))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1]]))

In [49]:
# Broadcast happens as expected
a + b

tensor([[0, 2],
        [2, 4],
        [4, 6]])