# 2.3. Linear Algebra

In this notebook, we will introduce the basic mathematical objects, arithmetic, and operations in linear algebra, expressing each of them through mathematical notation and the corresponding implementation in code.

## Table of Contents

[2.3.1 Scalars](#scalar)

[2.3.2 Vectors](#vector)

[2.3.3 Matrices](#matrix)

[2.3.4 Tensors](#tensor)

[2.3.5 Basic Properties of Tensor Arithmetic](#basic)

[2.3.6 Reduction](#reduction)

[2.3.7 Dot Products](#dot)

[2.3.8 Matrix-Vector Products](#mvprod)

[2.3.9 Matrix-Matrix Multiplication](#mmm)

[2.3.10 Norms](#norm)

[2.3.12 Summary](#summary)


## 2.3.1 Scalars <a name="scalar"></a>

A scalar is represented by a tensor with **just one element**.

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 Vectors <a name="vector"></a>

You can think of a vector as simply a list of scalar values. We call these values the **elements (entries or components) of the vector**. 

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
## We can refer to any element of a vector by using a subscript
x[2]

tensor(2)

In [5]:
## Length of the tensor
len(x)

torch.Size([4])

In [6]:
## Shape of the tensor
x.shape

torch.Size([4])

## 2.3.3 Matrices <a name="matrix"></a>

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
# Transpose the matrix
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
# Build a symmetric matrix 
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
# Check the property of symmetry
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 2.3.4 Tensors <a name="tensor"></a>

**Tensors** give us a generic way of describing 𝑛 -dimensional arrays with an arbitrary number of axes. For comparison, **vectors** are first-order tensors, and **matrices** are second-order tensors.

In [12]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5 Basic Properties of Tensor Arithmetic <a name="basic"></a>

In [13]:
## Elementwise addition of two matrices 
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # Assign a copy of `A` to `B` by allocating new memory
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [14]:
## Hadamard product: elementwise multiplication of two matrices
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [16]:
## Multiplying or adding a tensor by a scalar will perform elementwise multiplication and addition 
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [17]:
a * X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

## 2.3.6 Reduction <a name="reduction"></a>


In [18]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [20]:
A, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.))

In [21]:
## Specifying axis=0 will reduce the rows dimension (axis 1) by summing up elements of all the rows.
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [22]:
## Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns.
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [23]:
## Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.
A.sum(axis=[0, 1])  # Same as `A.sum()`

tensor(190.)

In [25]:
## Two ways of calculating mean
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

## 2.3.7 Dot Products <a name="dot"></a>

## 2.3.8 Matrix-Vector Products <a name="mvprod"></a>

## 2.3.9 Matrix-Matrix Multiplication <a name="mmm"></a>

## 2.3.10 Norms <a name="norm"></a>

## 2.3.12 Summary <a name="summary"></a>